services:
  client:
    build: 
      context: .
      dockerfile: Dockerfile-client
    environment:
      - WSCEX_SERVER_URL=ws://server:8081
      - WSCEX_TRACING_ENABLED=1
      - WSCEX_TRACING_JAEGER_ENDPOINT=jaeger:4318
    depends_on:
      - jaeger
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686"
      - "4318:4318"
    depends_on:
      - server
  server:
    build: 
      context: .
      dockerfile: Dockerfile-server
    ports:
      - "8080:8080"